export type Role = "JE" | "AE" | "XEN" | "JC" | "JC_CLERK" | "ADDL_COMMISSIONER" | "COMMISSIONER" | "FIELD_STAFF" | "BRANCH_OFFICER" | "GIS_LAB" | "ADMIN" | "VIEWER";
export type CaseStatus = "DRAFT" | "PENDING_AE" | "RETURNED_TO_JE" | "PENDING_JC" | "SCN_ISSUED" | "SCN_SERVED" | "RESPONSE_RECEIVED" | "RESPONSE_PENDING_AE" | "RESPONSE_PENDING_JC" | "NO_RESPONSE" | "HEARING_SCHEDULED" | "ORDER_ISSUED" | "ORDER_SERVED" | "APPEAL_STAY" | "EXECUTION_DUE" | "COMPLIED" | "EXECUTED" | "CLOSED" | "DROPPED" | "REGULARISED";

export interface Me { id: number; username: string; name: string; role: Role | null; designation: string; mobile: string; zones: Zone[]; wards: Ward[]; delegation_order_no: string; unread_notifications: number; permissions: string[]; branch: { code: string; name_en: string; name_hi: string } | null; }
export interface Zone { id: number; code: string; name_en: string; name_hi: string; active: boolean; }
export interface Ward { id: number; number: number; name_en: string; name_hi: string; zone: number; zone_code?: string; division: number | null; active: boolean; }
export interface UserLite { id: number; username: string; name: string; role: Role | null; designation: string; }
export interface ViolationType { code: string; category: string; title_en: string; title_hi: string; description: string; contravention_of: string; legal_basis: { statute: string; section: string }[]; action_path: string; orders_available: string[]; scn_response_days_default: number; order_compliance_days_default: number; statutory_minimum_days: number; severity: string; compoundable: string; evidence_checklist: string[]; schedule_fine_inr: number | null; schedule_daily_fine_inr: number | null; appeal: string; notes: string; active: boolean; }
export interface OrderType { code: string; title_en: string; title_hi: string; statute: string; section: string; kind: "NOTICE" | "ORDER" | "MEMO" | "REFERRAL"; min_days: number; default_days: number; template: string; appeal_days: number | null; appeal_to: string; active: boolean; }
export interface LegalSection { id: number; statute: string; statute_title: string; section: string; heading: string; kind: string; text: string; schedule_fine_inr: number | null; schedule_daily_fine_inr: number | null; verify: boolean; notes: string; }
export interface Media { id: string; case: string | null; notice: string | null; kind: string; media_type: string; url: string | null; original_name: string; size_bytes: number; sha256: string; latitude: string | null; longitude: string | null; accuracy_m: string | null; captured_at: string | null; device_id: string; distance_from_case_m: string | null; geotag_verified: boolean; integrity_status: "PASS" | "FLAGGED" | "REJECTED" | "UNVERIFIED"; integrity_reasons: string[]; caption: string; uploaded_by: UserLite | null; created_at: string; }
export interface Dispatch { id: number; channel: string; to: string; status: string; provider_ref: string; attempts: number; last_error: string; sent_at: string | null; created_at: string; }
export interface Notice { is_legacy?: boolean; id: string; case: string; case_no: string; order_type: OrderType; notice_no: string; kind: string; issued_by: UserLite; issued_at: string; addressee_name: string; addressee_address: string; addressee_mobiles: string[]; response_days: number; response_due_at: string | null; compliance_days: number; compliance_due_at: string | null; hearing_at: string | null; hearing_venue: string; operative_text_en: string; operative_text_hi: string; pdf_url: string | null; signed_pdf_url: string | null; document_hash: string; verification_code: string; qr_payload: string; signature_status: string; signer_name: string; signer_cert_subject: string; signed_at: string | null; signature_error: string; served_at: string | null; served_mode: string; served_by: UserLite | null; service_remarks: string; is_final_order: boolean; dispatches: Dispatch[]; delivery_media: Media[]; created_at: string; }
export interface CaseViolation { id: number; code: string; violation_type: ViolationType; details: Record<string, unknown>; remarks: string; is_primary: boolean; }
export interface CaseResponse { id: number; case: string; notice: string | null; notice_no?: string; received_on: string; received_via: string; submitted_by_name: string; summary: string; requests_hearing: boolean; is_within_time: boolean; uploaded_by: UserLite; ae_comments: string; ae_commented_at: string | null; jc_remarks: string; created_at: string; }
export interface Hearing { id: number; case: string; notice: string | null; scheduled_at: string; venue: string; presiding: UserLite; held_at: string | null; attendees: string; proceedings: string; outcome: string; next_date: string | null; }
export interface Appeal { id: number; case: string; order: string | null; order_no?: string | null; filed_on: string; authority: string; authority_display: string; authority_other: string; appeal_no: string; appellant_name: string; counsel_for_mcg: string; status: string; status_display: string; stay_granted: boolean; stay_order_date: string | null; stay_until: string | null; stay_scope: string; stay_order: Media | null; conditions: string; next_hearing_on: string | null; decided_on: string | null; decision_summary: string; final_order: Media | null; is_stay_active: boolean; recorded_by: UserLite; }
export interface Branch { code: string; name_en: string; name_hi: string; description: string; head_designation: string; default_response_days: number; active: boolean; officers: { user_id: number; name: string; designation: string }[]; }
export interface Referral { id: number; case: string; case_no: string; case_status: string; case_address: string; ward_number: number | null; branch: Branch; referred_by: UserLite; referred_at: string; query: string; due_at: string | null; hold_case: boolean; status: string; assigned_to: UserLite | null; response: string; recommendation: string; responded_by: UserLite | null; responded_at: string | null; closed_by: UserLite | null; closed_at: string | null; closing_remarks: string; is_overdue: boolean; created_at: string; }
export interface WorkflowSetting { key: string; value: any; value_type: string; label: string; description: string; group: string; choices: any[]; updated_at: string; }
export interface RulesMatrix { statuses: string[]; status_labels: Record<string, string>; roles: string[]; role_labels: Record<string, string>; actions: string[]; action_labels: Record<string, string>; management_roles: string[]; matrix: Record<string, Record<string, string[]>>; }
export interface PermMatrix { permissions: { code: string; label: string; group: string; default_roles: string[] }[]; roles: string[]; role_labels: Record<string, string>; management_roles: string[]; matrix: Record<string, string[]>; }
export interface AdminLog { id: number; at: string; actor: UserLite | null; action: string; target_type: string; target_id: string; before: any; after: any; order_reference: string; remarks: string; }
export interface Execution { id: number; case: string; order: string | null; action: string; mode: string; executed_on: string; squad_incharge: string; police_assistance: boolean; police_station: string; duty_magistrate: string; machinery_used: string; area_demolished_sqm: string | null; seal_memo_no: string; cost_incurred_inr: string | null; remarks: string; recorded_by: UserLite; verified_by: UserLite | null; verified_at: string | null; }
export interface CaseEvent { id: number; at: string; actor: UserLite | null; actor_role: string; action: string; from_status: string; to_status: string; remarks: string; payload: Record<string, unknown>; latitude: string | null; longitude: string | null; hash: string; prev_hash: string; }
export interface SanctionedPlan { id: number; plan_no: string; pid: string; address: string; ward: number | null; ward_number?: number; zone: number | null; latitude: string | null; longitude: string | null; owner_name: string; owner_mobile: string; plot_area_sqm: string | null; land_use: string; building_type: string; sanctioned_on: string; valid_till: string | null; sanction_mode: string; permitted_floors: string; permitted_ground_coverage_pct: string | null; permitted_far: string | null; permitted_height_m: string | null; setbacks: Record<string, number>; licence_no: string; licence_holder: string; licence_date: string | null; licence_valid_till: string | null; licence_authority: string; colony_name: string; architect_name: string; architect_registration_no: string; dpc_certificate_on: string | null; occupation_certificate_no: string; occupation_certificate_on: string | null; status: string; source: string; external_ref: string; remarks: string; documents?: Media[]; created_at: string; }
export interface GovtParcel { id: number; name: string; agency: string; land_use: string; village: string; khasra_no: string; area_sqm: string | null; ward: number | null; geometry: any; bbox: number[]; properties: Record<string, unknown>; active: boolean; }
export interface CaseListItem { id: string; case_no: string; status: CaseStatus; litigation_status: string; litigation_authority: string; stay_until: string | null; next_hearing_on: string | null; pending_referrals: string[]; status_display: string; priority: string; source: string; pid: string; address_line: string; locality: string; sector: string; ward: number | null; ward_number: number | null; zone: number | null; zone_code: string | null; latitude: string | null; longitude: string | null; land_type: string; owner_name: string; construction_stage: string; reported_by: UserLite; assigned_ae: UserLite | null; assigned_jc: UserLite | null; current_owner_role: Role; stage_due_at: string | null; sla_breached: boolean; inspected_at: string; scn_issued_at: string | null; response_due_at: string | null; compliance_due_at: string | null; decision: string; stop_work_issued: boolean; sealed: boolean; violation_codes: string[]; primary_violation: { code: string; title_en: string; category: string } | null; days_in_stage: number; thumbnail: string | null; created_at: string; updated_at: string; }
export interface CaseDetail extends CaseListItem { legacy_reference?: string; inspector_integrity?: IntegritySummary | null; complaint_ref: string; pid_snapshot: Record<string, any>; pid_linked_mobile: string; alternate_mobile: string; village_colony: string; pincode: string; division: number | null; location_accuracy_m: string | null; govt_parcel: GovtParcel | null; sanctioned_plan: SanctionedPlan | null; owner_father_name: string; occupier_name: string; builder_name: string; person_on_site: string; plot_area_sqm: string | null; covered_area_sqm: string | null; storeys: string; height_m: string | null; use_observed: string; description: string; measurements: Record<string, unknown>; submitted_at: string | null; ae_forwarded_at: string | null; jc_received_at: string | null; scn_served_at: string | null; response_received_at: string | null; hearing_at: string | null; decided_at: string | null; order_issued_at: string | null; order_served_at: string | null; executed_at: string | null; closed_at: string | null; decision_reasons: string; final_order: string | null; closure_reason: string; demolition_cost_inr: string | null; cost_recovery_status: string; violations: CaseViolation[]; media: Media[]; notices: Notice[]; responses: CaseResponse[]; hearings: Hearing[]; appeals: Appeal[]; executions: Execution[]; events: CaseEvent[]; referrals: Referral[]; available_actions: string[]; available_order_types: OrderType[]; }
export interface Paginated<T> { count: number; next: string | null; previous: string | null; results: T[]; }
export interface Summary { [k: string]: number; }
export interface Notification { id: number; case: string | null; case_no: string | null; title: string; body: string; level: string; read_at: string | null; created_at: string; }

export interface InspectionTask { id: number; batch: number | null; batch_title: string | null; category: string; category_display: string; pid: string; pid_snapshot: Record<string, any>; address: string; owner_name: string; owner_mobile: string; latitude: string | null; longitude: string | null; ward: number | null; ward_number: number | null; zone: number | null; zone_code: string | null; instructions: string; priority: string; created_by: UserLite; assigned_to: UserLite | null; assigned_at: string | null; due_at: string | null; status: string; status_display: string; related_case: string | null; related_case_no: string | null; started_at: string | null; start_latitude: string | null; start_longitude: string | null; start_distance_m: string | null; completed_at: string | null; outcome_remarks: string; geofence_m: number; case_no: string | null; case_id: string | null; case_status: string | null; is_overdue: boolean; media: Media[]; created_at: string; updated_at: string; }
export interface InspectionBatch { id: number; title: string; category: string; created_by: UserLite; instructions: string; due_at: string | null; total: number; errors: { row: number; error: string }[]; progress: Record<string, number>; created_at: string; }
export interface LandLayer { id: number; name: string; layer_key: string; version: number; replaces: number | null; agency: string; source_file: string; file_format: string; source: string; survey_date: string | null; feature_count: number; skipped_count: number; uploaded_by: UserLite | null; remarks: string; active: boolean; import_log: string; active_parcels: number; created_at: string; }

export interface IntegritySummary { id: number; at: string; decision: "PASS" | "FLAGGED" | "REJECTED"; reasons: string[]; flags: string[]; explanation: string; platform: string; source: string; native_module: boolean; attestation_status: string; device_model: string; app_version: string; accuracy_m: string | null; travel_speed_kmph: string | null; }
