import { useMemo } from "react";
import { WebView } from "react-native-webview";

/** Leaflet inside a WebView - identical to the map used by the MCG HARYANA app; works on iOS and
 *  Android without any Google Maps key. Government-land polygons + case points + optional marker. */
export default function LeafletMap({ govtLand, points, marker, onPointPress, onMapPress, center = [28.4595, 77.0266], zoom = 12 }: { govtLand?: any; points?: any; marker?: [number, number] | null; onPointPress?: (p: any) => void; onMapPress?: (lat: number, lng: number) => void; center?: [number, number]; zoom?: number }) {
  const html = useMemo(() => `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"/><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><style>html,body,#m{height:100%;margin:0}</style></head><body><div id="m"></div><script>
const map=L.map('m').setView(${JSON.stringify(center)},${zoom});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:20,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);
const colors={MCG:'#782669',HSVP:'#0d9488',GMDA:'#2563eb',STATE_GOVT:'#f59e0b',PWD:'#7c3aed',IRRIGATION:'#0891b2',FOREST:'#16a34a',PANCHAYAT:'#b45309',OTHER:'#6b7280'};
const land=${JSON.stringify(govtLand || null)};const pts=${JSON.stringify(points || null)};const marker=${JSON.stringify(marker || null)};
if(land){L.geoJSON(land,{style:f=>({color:colors[f.properties.agency]||'#6b7280',weight:f.properties.open_case_count?3:1.5,fillOpacity:f.properties.open_case_count?.4:.2,fillColor:f.properties.open_case_count?'#dc2626':(colors[f.properties.agency]||'#6b7280')}),onEachFeature:(f,l)=>{const p=f.properties;const cs=(p.cases||[]).map(c=>'<li><b>'+c.case_no+'</b> '+String(c.status).replace(/_/g,' ')+'</li>').join('');l.bindPopup('<b>'+(p.name||'Govt land')+'</b><br>'+(p.agency||'')+' '+(p.land_use||'')+(p.khasra_no?' · Khasra '+p.khasra_no:'')+'<div style="font-size:11px;margin-top:4px">'+(p.case_count||0)+' case(s), '+(p.open_case_count||0)+' open</div><ul style="font-size:11px;padding-left:14px;margin:2px 0">'+(cs||'<li>none</li>')+'</ul>');}}).addTo(map);}
const sc={DRAFT:'#9ca3af',PENDING_AE:'#2563eb',RETURNED_TO_JE:'#f59e0b',PENDING_JC:'#4338ca',SCN_ISSUED:'#a55cb4',SCN_SERVED:'#782669',RESPONSE_PENDING_AE:'#0e7490',RESPONSE_PENDING_JC:'#0e7490',NO_RESPONSE:'#c2410c',HEARING_SCHEDULED:'#6d28d9',ORDER_ISSUED:'#dc2626',ORDER_SERVED:'#b91c1c',APPEAL_STAY:'#334155',EXECUTION_DUE:'#7f1d1d',COMPLIED:'#16a34a',EXECUTED:'#15803d',CLOSED:'#6b7280',DROPPED:'#9ca3af',REGULARISED:'#059669',ASSIGNED:'#f59e0b',IN_PROGRESS:'#0d9488',VIOLATION_RECORDED:'#dc2626',NO_VIOLATION:'#16a34a'};
const esc=v=>String(v==null?'':v).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
if(pts){L.geoJSON(pts,{pointToLayer:(f,ll)=>f.properties.kind==='task'?L.marker(ll,{icon:L.divIcon({className:'',html:'<div style="width:14px;height:14px;transform:rotate(45deg);background:'+(sc[f.properties.status]||'#f59e0b')+';border:2px solid #fff"></div>',iconSize:[14,14],iconAnchor:[7,7]})}):L.circleMarker(ll,{radius:8,color:'#fff',weight:1.5,fillColor:sc[f.properties.status]||'#782669',fillOpacity:.95}),
onEachFeature:(f,l)=>{const p=f.properties;const hist=(p.history||[]).map(h=>'<li><span style="color:#6b7280">'+String(h.at).slice(0,16).replace('T',' ')+'</span> <b>'+esc(h.action).replace(/_/g,' ')+'</b></li>').join('');
l.bindPopup(p.kind==='task'?'<b>Planned inspection #'+p.id+'</b><br>'+esc(p.address)+'<br><span style="background:'+(sc[p.status]||'#999')+';color:#fff;border-radius:9px;padding:1px 6px;font-size:11px">'+esc(p.status_label||p.status)+'</span>':'<b style="color:#782669">'+esc(p.case_no)+'</b><br>'+esc(p.address)+'<br><span style="background:'+(sc[p.status]||'#999')+';color:#fff;border-radius:9px;padding:1px 6px;font-size:11px">'+esc(p.status_label||p.status)+'</span>'+(p.sealed?' <b style="color:#b45309">SEALED</b>':'')+(p.litigation==='STAYED'?' <b style="color:#334155">STAY</b>':'')+'<div style="font-size:11px;font-weight:600;margin-top:4px">History</div><ul style="font-size:11px;padding-left:14px;margin:2px 0;max-height:120px;overflow:auto">'+(hist||'<li>-</li>')+'</ul><a href="#" onclick="window.ReactNativeWebView.postMessage(JSON.stringify({type:\'point\',props:{id:\''+p.id+'\'}}));return false;" style="color:#0d9488;font-weight:600">Open case →</a>',{maxWidth:320});}}).addTo(map);}
if(marker){L.circleMarker(marker,{radius:10,color:'#fff',weight:3,fillColor:'#782669',fillOpacity:1}).addTo(map);map.setView(marker,17);}
map.on('click',e=>window.ReactNativeWebView.postMessage(JSON.stringify({type:'map',lat:e.latlng.lat,lng:e.latlng.lng})));
map.locate({setView:!marker&&!pts,maxZoom:16});map.on('locationfound',e=>L.circle(e.latlng,{radius:e.accuracy/2,color:'#0d9488',weight:1}).addTo(map));
</script></body></html>`, [govtLand, points, marker, center, zoom]);
  return <WebView originWhitelist={["*"]} source={{ html }} style={{ flex: 1 }} geolocationEnabled onMessage={(e) => { try { const m = JSON.parse(e.nativeEvent.data); if (m.type === "point") onPointPress?.(m.props); if (m.type === "map") onMapPress?.(m.lat, m.lng); } catch { /* ignore */ } }} />;
}
