# Generated by Django 5.2.17 on 2026-09-10 18:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_violations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=120)),
                ('name_hi', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('head_designation', models.CharField(blank=True, max_length=120)),
                ('default_response_days', models.PositiveSmallIntegerField(default=7)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'bvms_branch',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='appeal',
            options={'ordering': ['-filed_on', '-id']},
        ),
        migrations.AddField(
            model_name='appeal',
            name='appellant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appeal',
            name='authority_other',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appeal',
            name='counsel_for_mcg',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='appeal',
            name='final_order',
            field=models.ForeignKey(blank=True, help_text='Uploaded copy of the final order / judgment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='building_violations.mediaattachment'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='next_hearing_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='stay_order',
            field=models.ForeignKey(blank=True, help_text='Uploaded copy of the stay / interim order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='building_violations.mediaattachment'),
        ),
        migrations.AddField(
            model_name='appeal',
            name='stay_order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='stay_scope',
            field=models.CharField(blank=True, choices=[('FULL', 'All action stayed'), ('DEMOLITION_ONLY', 'Demolition stayed (sealing / stop-work continue)'), ('STATUS_QUO', 'Status quo (no construction, no demolition)'), ('PARTIAL', 'Partial - see conditions')], max_length=20),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='litigation_authority',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='litigation_status',
            field=models.CharField(db_index=True, default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='next_hearing_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='stay_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='appeal_no',
            field=models.CharField(blank=True, help_text='Appeal / CWP / SLP / OA number', max_length=120),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='authority',
            field=models.CharField(choices=[('DIVISIONAL_COMMISSIONER', 'Divisional Commissioner, Gurugram (s.261(2) / s.263A(4))'), ('COMMISSIONER_MCG', 'Commissioner, MCG (s.408B)'), ('CIVIL_COURT', 'Civil Court / District Court'), ('HIGH_COURT', 'Punjab & Haryana High Court'), ('SUPREME_COURT', 'Supreme Court of India'), ('NGT', 'National Green Tribunal'), ('OTHER', 'Other forum')], max_length=30),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending - no stay'), ('STAYED', 'Stay / status quo granted'), ('STAY_VACATED', 'Stay vacated'), ('DISMISSED', 'Dismissed'), ('ALLOWED', 'Allowed (order set aside)'), ('MODIFIED', 'Order modified'), ('WITHDRAWN', 'Withdrawn'), ('DISPOSED', 'Disposed with directions')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='stay_until',
            field=models.DateField(blank=True, help_text='Blank = until further orders / next date', null=True),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='kind',
            field=models.CharField(choices=[('INSPECTION', 'Inspection evidence'), ('NOTICE_DELIVERY', 'Proof of delivery of notice'), ('ORDER_DELIVERY', 'Proof of delivery of order'), ('RESPONSE', 'Response / reply document'), ('HEARING', 'Hearing record'), ('EXECUTION', 'Demolition / sealing evidence'), ('COMPLIANCE', 'Self-compliance evidence'), ('APPEAL', 'Appeal memo / pleadings'), ('STAY_ORDER', 'Stay / interim order of the appellate authority or court'), ('COURT_ORDER', 'Final order / judgment'), ('SANCTION_DOC', 'Sanction / licence document'), ('BRANCH_REFERRAL', 'Document sent with a branch referral'), ('BRANCH_RESPONSE', 'Branch response / report'), ('OTHER', 'Other')], default='INSPECTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='role',
            field=models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='escalate_to_role',
            field=models.CharField(blank=True, choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='violationcase',
            name='current_owner_role',
            field=models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], default='JE', max_length=24),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('action', models.CharField(max_length=40)),
                ('target_type', models.CharField(blank=True, max_length=40)),
                ('target_id', models.CharField(blank=True, max_length=60)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('order_reference', models.CharField(blank=True, max_length=120)),
                ('remarks', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_admin_audit_log',
                'ordering': ['-at'],
            },
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='For BRANCH_OFFICER: the branch this officer answers for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='building_violations.branch'),
        ),
        migrations.CreateModel(
            name='BranchReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('query', models.TextField(help_text='What the branch is asked to examine / report on')),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('hold_case', models.BooleanField(default=False, help_text='If true, final orders are blocked until the branch responds (subject to workflow setting)')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting branch response'), ('RESPONDED', 'Response received'), ('CLOSED', 'Closed by referring officer'), ('WITHDRAWN', 'Withdrawn')], db_index=True, default='PENDING', max_length=12)),
                ('response', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, max_length=40)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closing_remarks', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bvms_referrals_assigned', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='building_violations.branch')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='building_violations.violationcase')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bvms_referrals_made', to=settings.AUTH_USER_MODEL)),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bvms_referrals_answered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_branch_referral',
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowSetting',
            fields=[
                ('key', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('value_type', models.CharField(default='bool', max_length=10)),
                ('label', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('group', models.CharField(default='Routing', max_length=40)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_workflow_setting',
                'ordering': ['group', 'key'],
            },
        ),
        migrations.CreateModel(
            name='OfficerPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=40)),
                ('allowed', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('order_reference', models.CharField(blank=True, help_text="Office order / Commissioner's order authorising the change", max_length=120)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='building_violations.officerprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_officer_permission_override',
                'unique_together': {('profile', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24)),
                ('permission', models.CharField(max_length=40)),
                ('allowed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_role_permission',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=30)),
                ('role', models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24)),
                ('action', models.CharField(max_length=40)),
                ('allowed', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_workflow_rule',
                'unique_together': {('status', 'role', 'action')},
            },
        ),
    ]
