# Generated by Django 5.2.17 on 2026-09-10 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_violations', '0002_branch_alter_appeal_options_appeal_appellant_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlayerupload',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='govtlandparcel',
            name='layer_key',
            field=models.SlugField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='file_format',
            field=models.CharField(choices=[('GEOJSON', 'GeoJSON'), ('KML', 'KML / KMZ'), ('SHP_ZIP', 'Zipped shapefile')], default='GEOJSON', max_length=10),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='import_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='layer_key',
            field=models.SlugField(default='', help_text='Stable id of the layer, e.g. mcg-green-belts; re-uploads with the same key replace the old version', max_length=80),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='building_violations.landlayerupload'),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='skipped_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Revenue record / survey / drone / DTP layout ...', max_length=200),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='survey_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlayerupload',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='inspector_distance_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='inspector_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text="Officer's device location at the time of recording", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='inspector_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='landlayerupload',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='kind',
            field=models.CharField(choices=[('INSPECTION', 'Inspection evidence'), ('NOTICE_DELIVERY', 'Proof of delivery of notice'), ('ORDER_DELIVERY', 'Proof of delivery of order'), ('RESPONSE', 'Response / reply document'), ('HEARING', 'Hearing record'), ('EXECUTION', 'Demolition / sealing evidence'), ('COMPLIANCE', 'Self-compliance evidence'), ('APPEAL', 'Appeal memo / pleadings'), ('STAY_ORDER', 'Stay / interim order of the appellate authority or court'), ('COURT_ORDER', 'Final order / judgment'), ('SANCTION_DOC', 'Sanction / licence document'), ('TASK_EVIDENCE', 'Planned-inspection evidence (no violation / not found)'), ('BRANCH_REFERRAL', 'Document sent with a branch referral'), ('BRANCH_RESPONSE', 'Branch response / report'), ('OTHER', 'Other')], default='INSPECTION', max_length=20),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='role',
            field=models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('GIS_LAB', 'GIS lab - maintains government-land and ward layers'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('GIS_LAB', 'GIS lab - maintains government-land and ward layers'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='slaconfig',
            name='escalate_to_role',
            field=models.CharField(blank=True, choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('GIS_LAB', 'GIS lab - maintains government-land and ward layers'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='violationcase',
            name='current_owner_role',
            field=models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('GIS_LAB', 'GIS lab - maintains government-land and ward layers'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], default='JE', max_length=24),
        ),
        migrations.AlterField(
            model_name='workflowrule',
            name='role',
            field=models.CharField(choices=[('JE', 'Junior Engineer (field)'), ('AE', 'Assistant Engineer'), ('XEN', 'Executive Engineer'), ('JC', 'Joint Commissioner'), ('JC_CLERK', 'JC office clerk (response upload only)'), ('ADDL_COMMISSIONER', 'Additional Commissioner'), ('COMMISSIONER', 'Commissioner'), ('FIELD_STAFF', 'Enforcement / demolition squad'), ('BRANCH_OFFICER', 'Branch officer (Planning / Revenue / Legal ...) - consulted on cases'), ('GIS_LAB', 'GIS lab - maintains government-land and ward layers'), ('ADMIN', 'Module administrator'), ('VIEWER', 'Read-only (MIS)')], max_length=24),
        ),
        migrations.CreateModel(
            name='InspectionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='VERIFICATION', max_length=40)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='bvms/inspection-batches/')),
                ('instructions', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_inspection_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('VERIFICATION', 'Routine verification'), ('PG_HOSTEL', 'Paying guest / hostel check'), ('COMPLAINT', 'Complaint verification'), ('DRONE_FLAG', 'Drone / satellite change detection'), ('COURT_DIRECTION', 'Court / appellate direction'), ('SANCTION_FOLLOWUP', 'Sanctioned plan follow-up (DPC / completion)'), ('GOVT_LAND', 'Government land watch'), ('RE_INSPECTION', 'Re-inspection of an existing case'), ('OTHER', 'Other')], default='VERIFICATION', max_length=24)),
                ('pid', models.CharField(blank=True, db_index=True, max_length=40)),
                ('pid_snapshot', models.JSONField(blank=True, default=dict)),
                ('address', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('owner_mobile', models.CharField(blank=True, max_length=15)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('instructions', models.TextField(blank=True, help_text='What the field officer must check')),
                ('priority', models.CharField(default='NORMAL', max_length=10)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Awaiting assignment'), ('IN_PROGRESS', 'Inspection started on site'), ('VIOLATION_RECORDED', 'Violation recorded (case created)'), ('NO_VIOLATION', 'Inspected - no violation'), ('NOT_FOUND', 'Property not traceable'), ('CANCELLED', 'Cancelled')], db_index=True, default='UNASSIGNED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('start_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('start_distance_m', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_remarks', models.TextField(blank=True)),
                ('geofence_m', models.PositiveIntegerField(default=100, help_text='Officer must be within this many metres of the point to start')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bvms_tasks', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='building_violations.inspectionbatch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bvms_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('related_case', models.ForeignKey(blank=True, help_text='For re-inspection tasks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_tasks', to='building_violations.violationcase')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='building_violations.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='building_violations.zone')),
            ],
            options={
                'db_table': 'bvms_inspection_task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='building_violations.inspectiontask'),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case', to='building_violations.inspectiontask'),
        ),
        migrations.AddIndex(
            model_name='inspectiontask',
            index=models.Index(fields=['assigned_to', 'status'], name='bvms_inspec_assigne_b3fd77_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontask',
            index=models.Index(fields=['status', 'zone'], name='bvms_inspec_status_056076_idx'),
        ),
    ]
