# Generated by Django 5.2.17 on 2026-09-11 08:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_violations', '0004_location_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='is_legacy',
            field=models.BooleanField(default=False, help_text='Issued on paper before the system; original number / date / signatory kept, scanned copy attached'),
        ),
        migrations.AddField(
            model_name='violationcase',
            name='legacy_reference',
            field=models.CharField(blank=True, help_text='Register / file reference of an order issued before the system', max_length=120),
        ),
        migrations.AlterField(
            model_name='govtlandparcel',
            name='agency',
            field=models.CharField(choices=[('MCG', 'Municipal Corporation Gurugram'), ('HSVP', 'Haryana Shahari Vikas Pradhikaran'), ('GMDA', 'Gurugram Metropolitan Development Authority'), ('STATE_GOVT', 'State Government (other departments)'), ('PWD', 'PWD (B&R)'), ('IRRIGATION', 'Irrigation & Water Resources'), ('FOREST', 'Forest Department'), ('PANCHAYAT', 'Gram Panchayat / Shamlat Deh'), ('RAILWAYS', 'Railways'), ('NHAI', 'NHAI'), ('DEFENCE', 'Defence'), ('LEGACY_ORDER', 'Scanned copy of an order issued before the system'), ('OTHER', 'Other')], default='MCG', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlayerupload',
            name='agency',
            field=models.CharField(choices=[('MCG', 'Municipal Corporation Gurugram'), ('HSVP', 'Haryana Shahari Vikas Pradhikaran'), ('GMDA', 'Gurugram Metropolitan Development Authority'), ('STATE_GOVT', 'State Government (other departments)'), ('PWD', 'PWD (B&R)'), ('IRRIGATION', 'Irrigation & Water Resources'), ('FOREST', 'Forest Department'), ('PANCHAYAT', 'Gram Panchayat / Shamlat Deh'), ('RAILWAYS', 'Railways'), ('NHAI', 'NHAI'), ('DEFENCE', 'Defence'), ('LEGACY_ORDER', 'Scanned copy of an order issued before the system'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.CreateModel(
            name='LegacyOrderBatch',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='bvms/legacy/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_legacy_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='violationcase',
            name='legacy_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='building_violations.legacyorderbatch'),
        ),
    ]
