"""review hierarchy roles and stages

Revision ID: 2eb08428ec2a
Revises: d133337c5b13
Create Date: 2026-09-11 22:46:53.563092
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '2eb08428ec2a'
down_revision = 'd133337c5b13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bvms_review_stage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('slot', sa.String(length=10), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_hi', sa.String(length=120), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_review_stage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_review_stage_role'), ['role'], unique=False)

    op.create_table('bvms_role',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('label_en', sa.String(length=120), nullable=False),
    sa.Column('label_hi', sa.String(length=120), nullable=False),
    sa.Column('short_label', sa.String(length=24), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('bvms_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_stage', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bvms_case', schema=None) as batch_op:
        batch_op.drop_column('review_stage')

    op.drop_table('bvms_role')
    with op.batch_alter_table('bvms_review_stage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_review_stage_role'))

    op.drop_table('bvms_review_stage')
    # ### end Alembic commands ###
