"""initial schema (FastAPI edition)

Revision ID: d133337c5b13
Revises: 
Create Date: 2026-09-11 21:17:03.578441
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'd133337c5b13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bvms_branch',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('head_designation', sa.String(length=120), nullable=False),
    sa.Column('default_response_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('bvms_legal_statute',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('citation', sa.String(length=300), nullable=False),
    sa.Column('jurisdiction', sa.String(length=200), nullable=False),
    sa.Column('primary', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('bvms_order_type',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('title_en', sa.String(length=250), nullable=False),
    sa.Column('title_hi', sa.String(length=250), nullable=False),
    sa.Column('statute', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('default_days', sa.Integer(), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('appeal_days', sa.Integer(), nullable=True),
    sa.Column('appeal_to', sa.String(length=200), nullable=False),
    sa.Column('body_override_en', sa.Text(), nullable=False),
    sa.Column('body_override_hi', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('bvms_otp',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_otp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_otp_mobile'), ['mobile'], unique=False)

    op.create_table('bvms_sequence',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bvms_sla_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('escalate_to_role', sa.String(length=24), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage')
    )
    op.create_table('bvms_violation_type',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('title_en', sa.String(length=250), nullable=False),
    sa.Column('title_hi', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contravention_of', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.JSON(), nullable=False),
    sa.Column('action_path', sa.String(length=30), nullable=False),
    sa.Column('orders_available', sa.JSON(), nullable=False),
    sa.Column('scn_response_days_default', sa.Integer(), nullable=False),
    sa.Column('order_compliance_days_default', sa.Integer(), nullable=False),
    sa.Column('statutory_minimum_days', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('compoundable', sa.String(length=12), nullable=False),
    sa.Column('evidence_checklist', sa.JSON(), nullable=False),
    sa.Column('schedule_fine_inr', sa.Integer(), nullable=True),
    sa.Column('schedule_daily_fine_inr', sa.Integer(), nullable=True),
    sa.Column('appeal', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('bvms_zone',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_hi', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('bvms_admin_audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.String(length=60), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('after', sa.JSON(), nullable=False),
    sa.Column('order_reference', sa.String(length=120), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_admin_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_admin_audit_log_at'), ['at'], unique=False)

    op.create_table('bvms_app_attest_key',
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('counter', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('environment', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('key_id')
    )
    op.create_table('bvms_division',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['zone_id'], ['bvms_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('bvms_inspection_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('source_file', sa.String(length=300), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bvms_integrity_nonce',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('bvms_land_layer_upload',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('layer_key', sa.String(length=80), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('replaces_id', sa.Integer(), nullable=True),
    sa.Column('agency', sa.String(length=20), nullable=False),
    sa.Column('source_file', sa.String(length=300), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('feature_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('import_log', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['replaces_id'], ['bvms_land_layer_upload.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_land_layer_upload', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_land_layer_upload_layer_key'), ['layer_key'], unique=False)

    op.create_table('bvms_legacy_batch',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('source_file', sa.String(length=300), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Integer(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bvms_legal_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('statute_id', sa.String(length=20), nullable=False),
    sa.Column('section', sa.String(length=30), nullable=False),
    sa.Column('heading', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('schedule_fine_inr', sa.Integer(), nullable=True),
    sa.Column('schedule_daily_fine_inr', sa.Integer(), nullable=True),
    sa.Column('verify', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['statute_id'], ['bvms_legal_statute.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('statute_id', 'section')
    )
    op.create_table('bvms_officer_profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('reports_to_id', sa.Integer(), nullable=True),
    sa.Column('delegation_order_no', sa.String(length=120), nullable=False),
    sa.Column('delegation_order_date', sa.Date(), nullable=True),
    sa.Column('signature_image', sa.String(length=300), nullable=False),
    sa.Column('parent_profile_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['bvms_branch.code'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_profile_id'], ['bvms_officer_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reports_to_id'], ['bvms_officer_profile.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('bvms_officer_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_officer_profile_mobile'), ['mobile'], unique=False)

    op.create_table('bvms_role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('permission', sa.String(length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role', 'permission')
    )
    op.create_table('bvms_workflow_rule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status', 'role', 'action')
    )
    op.create_table('bvms_workflow_setting',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('value_type', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=40), nullable=False),
    sa.Column('choices', sa.JSON(), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('bvms_officer_permission_override',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=40), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('order_reference', sa.String(length=120), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['bvms_officer_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'permission')
    )
    op.create_table('bvms_officer_profile_divisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officerprofile_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['bvms_division.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['officerprofile_id'], ['bvms_officer_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officerprofile_id', 'division_id')
    )
    op.create_table('bvms_officer_profile_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officerprofile_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['officerprofile_id'], ['bvms_officer_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['bvms_zone.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officerprofile_id', 'zone_id')
    )
    op.create_table('bvms_ward',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.Column('name_hi', sa.String(length=120), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['bvms_division.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['bvms_zone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('bvms_govt_land_parcel',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('agency', sa.String(length=20), nullable=False),
    sa.Column('land_use', sa.String(length=120), nullable=False),
    sa.Column('village', sa.String(length=120), nullable=False),
    sa.Column('khasra_no', sa.String(length=120), nullable=False),
    sa.Column('area_sqm', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=False),
    sa.Column('bbox', sa.JSON(), nullable=False),
    sa.Column('properties', sa.JSON(), nullable=False),
    sa.Column('layer_upload_id', sa.Integer(), nullable=True),
    sa.Column('layer_key', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['layer_upload_id'], ['bvms_land_layer_upload.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['bvms_ward.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_govt_land_parcel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_govt_land_parcel_layer_key'), ['layer_key'], unique=False)

    op.create_table('bvms_inspection_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('pid', sa.String(length=40), nullable=False),
    sa.Column('pid_snapshot', sa.JSON(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_mobile', sa.String(length=15), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('related_case_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('start_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('start_distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_remarks', sa.Text(), nullable=False),
    sa.Column('geofence_m', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['batch_id'], ['bvms_inspection_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['related_case_id'], ['bvms_case.id'], name='fk_task_related_case', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['ward_id'], ['bvms_ward.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['bvms_zone.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_inspection_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_inspection_task_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_inspection_task_pid'), ['pid'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_inspection_task_status'), ['status'], unique=False)
        batch_op.create_index('ix_bvms_task_assigned_status', ['assigned_to_id', 'status'], unique=False)
        batch_op.create_index('ix_bvms_task_status_zone', ['status', 'zone_id'], unique=False)

    op.create_table('bvms_officer_profile_wards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('officerprofile_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['officerprofile_id'], ['bvms_officer_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ward_id'], ['bvms_ward.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('officerprofile_id', 'ward_id')
    )
    op.create_table('bvms_sanctioned_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_no', sa.String(length=80), nullable=False),
    sa.Column('pid', sa.String(length=40), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_mobile', sa.String(length=15), nullable=False),
    sa.Column('plot_area_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('land_use', sa.String(length=60), nullable=False),
    sa.Column('building_type', sa.String(length=80), nullable=False),
    sa.Column('sanctioned_on', sa.Date(), nullable=False),
    sa.Column('valid_till', sa.Date(), nullable=True),
    sa.Column('sanction_mode', sa.String(length=40), nullable=False),
    sa.Column('permitted_floors', sa.String(length=40), nullable=False),
    sa.Column('permitted_ground_coverage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('permitted_far', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('permitted_height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('setbacks', sa.JSON(), nullable=False),
    sa.Column('licence_no', sa.String(length=80), nullable=False),
    sa.Column('licence_holder', sa.String(length=200), nullable=False),
    sa.Column('licence_date', sa.Date(), nullable=True),
    sa.Column('licence_valid_till', sa.Date(), nullable=True),
    sa.Column('licence_authority', sa.String(length=120), nullable=False),
    sa.Column('colony_name', sa.String(length=160), nullable=False),
    sa.Column('architect_name', sa.String(length=160), nullable=False),
    sa.Column('architect_registration_no', sa.String(length=80), nullable=False),
    sa.Column('dpc_certificate_on', sa.Date(), nullable=True),
    sa.Column('occupation_certificate_no', sa.String(length=80), nullable=False),
    sa.Column('occupation_certificate_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('external_ref', sa.String(length=120), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['bvms_ward.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['bvms_zone.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_no')
    )
    with op.batch_alter_table('bvms_sanctioned_plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_sanctioned_plan_pid'), ['pid'], unique=False)

    op.create_table('bvms_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_no', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('status_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('legacy_reference', sa.String(length=120), nullable=False),
    sa.Column('legacy_batch_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('complaint_ref', sa.String(length=80), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('pid', sa.String(length=40), nullable=False),
    sa.Column('pid_snapshot', sa.JSON(), nullable=False),
    sa.Column('pid_linked_mobile', sa.String(length=15), nullable=False),
    sa.Column('alternate_mobile', sa.String(length=15), nullable=False),
    sa.Column('address_line', sa.Text(), nullable=False),
    sa.Column('locality', sa.String(length=160), nullable=False),
    sa.Column('sector', sa.String(length=60), nullable=False),
    sa.Column('village_colony', sa.String(length=160), nullable=False),
    sa.Column('pincode', sa.String(length=6), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('location_accuracy_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('land_type', sa.String(length=12), nullable=False),
    sa.Column('govt_parcel_id', sa.Integer(), nullable=True),
    sa.Column('sanctioned_plan_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(length=200), nullable=False),
    sa.Column('owner_father_name', sa.String(length=200), nullable=False),
    sa.Column('occupier_name', sa.String(length=200), nullable=False),
    sa.Column('builder_name', sa.String(length=200), nullable=False),
    sa.Column('person_on_site', sa.String(length=200), nullable=False),
    sa.Column('construction_stage', sa.String(length=20), nullable=False),
    sa.Column('plot_area_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('covered_area_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('storeys', sa.String(length=40), nullable=False),
    sa.Column('height_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('use_observed', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('measurements', sa.JSON(), nullable=False),
    sa.Column('reported_by_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_ae_id', sa.Uuid(), nullable=True),
    sa.Column('assigned_jc_id', sa.Uuid(), nullable=True),
    sa.Column('current_owner_role', sa.String(length=24), nullable=False),
    sa.Column('stage_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_breached', sa.Boolean(), nullable=False),
    sa.Column('inspected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ae_forwarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jc_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scn_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scn_served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hearing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('inspector_latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('inspector_longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('inspector_distance_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('litigation_status', sa.String(length=20), nullable=False),
    sa.Column('litigation_authority', sa.String(length=30), nullable=False),
    sa.Column('stay_until', sa.Date(), nullable=True),
    sa.Column('next_hearing_on', sa.Date(), nullable=True),
    sa.Column('stop_work_issued', sa.Boolean(), nullable=False),
    sa.Column('sealed', sa.Boolean(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('decision_reasons', sa.Text(), nullable=False),
    sa.Column('final_order_id', sa.Uuid(), nullable=True),
    sa.Column('closure_reason', sa.Text(), nullable=False),
    sa.Column('demolition_cost_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cost_recovery_status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['assigned_ae_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_jc_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['division_id'], ['bvms_division.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['final_order_id'], ['bvms_notice.id'], name='fk_case_final_order', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['govt_parcel_id'], ['bvms_govt_land_parcel.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['legacy_batch_id'], ['bvms_legacy_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sanctioned_plan_id'], ['bvms_sanctioned_plan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['bvms_inspection_task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ward_id'], ['bvms_ward.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['bvms_zone.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id')
    )
    with op.batch_alter_table('bvms_case', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_case_case_no'), ['case_no'], unique=True)
        batch_op.create_index('ix_bvms_case_compliance_due', ['compliance_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_case_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_bvms_case_land_type', ['land_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_case_litigation_status'), ['litigation_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_case_pid'), ['pid'], unique=False)
        batch_op.create_index('ix_bvms_case_response_due', ['response_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_case_status'), ['status'], unique=False)
        batch_op.create_index('ix_bvms_case_status_zone', ['status', 'zone_id'], unique=False)
        batch_op.create_index('ix_bvms_case_ward_status', ['ward_id', 'status'], unique=False)

    op.create_table('bvms_branch_referral',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('branch_id', sa.String(length=20), nullable=False),
    sa.Column('referred_by_id', sa.Uuid(), nullable=False),
    sa.Column('referred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hold_case', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('assigned_to_id', sa.Uuid(), nullable=True),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.String(length=40), nullable=False),
    sa.Column('responded_by_id', sa.Uuid(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_by_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_remarks', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['branch_id'], ['bvms_branch.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['closed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referred_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['responded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_branch_referral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_branch_referral_status'), ['status'], unique=False)

    op.create_table('bvms_case_event',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('from_status', sa.String(length=30), nullable=False),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_case_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_case_event_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_case_event_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_case_event_hash'), ['hash'], unique=False)

    op.create_table('bvms_case_violation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('violation_type_id', sa.String(length=10), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['violation_type_id'], ['bvms_violation_type.code'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'violation_type_id')
    )
    op.create_table('bvms_location_integrity',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('officer_id', sa.Uuid(), nullable=True),
    sa.Column('context', sa.String(length=14), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('flags', sa.JSON(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('media_id', sa.Uuid(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('altitude_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('speed_mps', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('heading', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('fix_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fix_age_s', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('jitter_m', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('platform', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('app_version', sa.String(length=40), nullable=False),
    sa.Column('build_number', sa.String(length=40), nullable=False),
    sa.Column('os_version', sa.String(length=40), nullable=False),
    sa.Column('device_model', sa.String(length=80), nullable=False),
    sa.Column('native_module', sa.Boolean(), nullable=False),
    sa.Column('is_physical_device', sa.Boolean(), nullable=True),
    sa.Column('mock_location', sa.Boolean(), nullable=True),
    sa.Column('rooted', sa.Boolean(), nullable=True),
    sa.Column('developer_options', sa.Boolean(), nullable=True),
    sa.Column('vpn_active', sa.Boolean(), nullable=True),
    sa.Column('proxy_configured', sa.Boolean(), nullable=True),
    sa.Column('simulated_by_software', sa.Boolean(), nullable=True),
    sa.Column('produced_by_accessory', sa.Boolean(), nullable=True),
    sa.Column('attestation_type', sa.String(length=20), nullable=False),
    sa.Column('attestation_status', sa.String(length=12), nullable=False),
    sa.Column('attestation_detail', sa.JSON(), nullable=False),
    sa.Column('client_ip', sa.String(length=45), nullable=True),
    sa.Column('ip_intel', sa.JSON(), nullable=False),
    sa.Column('ip_distance_km', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('previous_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('travel_distance_km', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('travel_speed_kmph', sa.Numeric(precision=10, scale=1), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['bvms_media.id'], name='fk_li_media', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['previous_id'], ['bvms_location_integrity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['bvms_inspection_task.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_location_integrity', schema=None) as batch_op:
        batch_op.create_index('ix_bvms_li_decision_at', ['decision', 'at'], unique=False)
        batch_op.create_index('ix_bvms_li_officer_at', ['officer_id', 'at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_location_integrity_at'), ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_location_integrity_decision'), ['decision'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_location_integrity_fix_at'), ['fix_at'], unique=False)

    op.create_table('bvms_notice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('order_type_id', sa.String(length=40), nullable=False),
    sa.Column('notice_no', sa.String(length=60), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=False),
    sa.Column('issued_by_id', sa.Uuid(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('addressee_name', sa.String(length=200), nullable=False),
    sa.Column('addressee_address', sa.Text(), nullable=False),
    sa.Column('addressee_mobiles', sa.JSON(), nullable=False),
    sa.Column('response_days', sa.Integer(), nullable=False),
    sa.Column('response_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('compliance_days', sa.Integer(), nullable=False),
    sa.Column('compliance_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hearing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hearing_venue', sa.String(length=200), nullable=False),
    sa.Column('operative_text_en', sa.Text(), nullable=False),
    sa.Column('operative_text_hi', sa.Text(), nullable=False),
    sa.Column('html_snapshot', sa.Text(), nullable=False),
    sa.Column('context_snapshot', sa.JSON(), nullable=False),
    sa.Column('pdf', sa.String(length=300), nullable=False),
    sa.Column('signed_pdf', sa.String(length=300), nullable=False),
    sa.Column('document_hash', sa.String(length=64), nullable=False),
    sa.Column('verification_code', sa.String(length=24), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('signature_status', sa.String(length=10), nullable=False),
    sa.Column('signer_name', sa.String(length=200), nullable=False),
    sa.Column('signer_cert_subject', sa.String(length=300), nullable=False),
    sa.Column('signer_cert_serial', sa.String(length=120), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signature_error', sa.Text(), nullable=False),
    sa.Column('served_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('served_mode', sa.String(length=16), nullable=False),
    sa.Column('served_by_id', sa.Uuid(), nullable=True),
    sa.Column('service_remarks', sa.Text(), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_final_order', sa.Boolean(), nullable=False),
    sa.Column('is_legacy', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_type_id'], ['bvms_order_type.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['served_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['bvms_notice.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_notice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_notice_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_notice_document_hash'), ['document_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_notice_notice_no'), ['notice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_bvms_notice_verification_code'), ['verification_code'], unique=True)

    op.create_table('bvms_notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_notification_user_id'), ['user_id'], unique=False)

    op.create_table('bvms_case_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=True),
    sa.Column('received_on', sa.Date(), nullable=False),
    sa.Column('received_via', sa.String(length=10), nullable=False),
    sa.Column('submitted_by_name', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('requests_hearing', sa.Boolean(), nullable=False),
    sa.Column('is_within_time', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('ae_comments', sa.Text(), nullable=False),
    sa.Column('ae_commented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('jc_remarks', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['bvms_notice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bvms_execution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=12), nullable=False),
    sa.Column('executed_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('squad_incharge', sa.String(length=200), nullable=False),
    sa.Column('police_assistance', sa.Boolean(), nullable=False),
    sa.Column('police_station', sa.String(length=120), nullable=False),
    sa.Column('duty_magistrate', sa.String(length=200), nullable=False),
    sa.Column('machinery_used', sa.String(length=300), nullable=False),
    sa.Column('area_demolished_sqm', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('seal_memo_no', sa.String(length=60), nullable=False),
    sa.Column('cost_incurred_inr', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.Column('verified_by_id', sa.Uuid(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['bvms_notice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bvms_hearing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('venue', sa.String(length=200), nullable=False),
    sa.Column('presiding_id', sa.Uuid(), nullable=False),
    sa.Column('held_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attendees', sa.Text(), nullable=False),
    sa.Column('proceedings', sa.Text(), nullable=False),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('next_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['notice_id'], ['bvms_notice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['presiding_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bvms_media',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('notice_id', sa.Uuid(), nullable=True),
    sa.Column('sanctioned_plan_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('media_type', sa.String(length=10), nullable=False),
    sa.Column('file', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('accuracy_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('altitude_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('device_id', sa.String(length=120), nullable=False),
    sa.Column('distance_from_case_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('geotag_verified', sa.Boolean(), nullable=False),
    sa.Column('integrity_status', sa.String(length=12), nullable=False),
    sa.Column('integrity_check_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('caption', sa.String(length=300), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integrity_check_id'], ['bvms_location_integrity.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notice_id'], ['bvms_notice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sanctioned_plan_id'], ['bvms_sanctioned_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['bvms_inspection_task.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bvms_media', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bvms_media_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_media_integrity_status'), ['integrity_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bvms_media_sha256'), ['sha256'], unique=False)

    op.create_table('bvms_notice_dispatch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notice_id', sa.Uuid(), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('to', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('provider_ref', sa.String(length=120), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notice_id'], ['bvms_notice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bvms_appeal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('authority', sa.String(length=30), nullable=False),
    sa.Column('authority_other', sa.String(length=200), nullable=False),
    sa.Column('filed_on', sa.Date(), nullable=False),
    sa.Column('appeal_no', sa.String(length=120), nullable=False),
    sa.Column('appellant_name', sa.String(length=200), nullable=False),
    sa.Column('counsel_for_mcg', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('stay_granted', sa.Boolean(), nullable=False),
    sa.Column('stay_order_date', sa.Date(), nullable=True),
    sa.Column('stay_until', sa.Date(), nullable=True),
    sa.Column('stay_scope', sa.String(length=20), nullable=False),
    sa.Column('stay_order_id', sa.Uuid(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=False),
    sa.Column('next_hearing_on', sa.Date(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.Column('decision_summary', sa.Text(), nullable=False),
    sa.Column('final_order_id', sa.Uuid(), nullable=True),
    sa.Column('recorded_by_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['bvms_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['final_order_id'], ['bvms_media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['bvms_notice.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stay_order_id'], ['bvms_media.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bvms_appeal')
    op.drop_table('bvms_notice_dispatch')
    with op.batch_alter_table('bvms_media', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_media_sha256'))
        batch_op.drop_index(batch_op.f('ix_bvms_media_integrity_status'))
        batch_op.drop_index(batch_op.f('ix_bvms_media_case_id'))

    op.drop_table('bvms_media')
    op.drop_table('bvms_hearing')
    op.drop_table('bvms_execution')
    op.drop_table('bvms_case_response')
    with op.batch_alter_table('bvms_notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_bvms_notification_created_at'))

    op.drop_table('bvms_notification')
    with op.batch_alter_table('bvms_notice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_notice_verification_code'))
        batch_op.drop_index(batch_op.f('ix_bvms_notice_notice_no'))
        batch_op.drop_index(batch_op.f('ix_bvms_notice_document_hash'))
        batch_op.drop_index(batch_op.f('ix_bvms_notice_case_id'))

    op.drop_table('bvms_notice')
    with op.batch_alter_table('bvms_location_integrity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_location_integrity_fix_at'))
        batch_op.drop_index(batch_op.f('ix_bvms_location_integrity_decision'))
        batch_op.drop_index(batch_op.f('ix_bvms_location_integrity_at'))
        batch_op.drop_index('ix_bvms_li_officer_at')
        batch_op.drop_index('ix_bvms_li_decision_at')

    op.drop_table('bvms_location_integrity')
    op.drop_table('bvms_case_violation')
    with op.batch_alter_table('bvms_case_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_case_event_hash'))
        batch_op.drop_index(batch_op.f('ix_bvms_case_event_case_id'))
        batch_op.drop_index(batch_op.f('ix_bvms_case_event_at'))

    op.drop_table('bvms_case_event')
    with op.batch_alter_table('bvms_branch_referral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_branch_referral_status'))

    op.drop_table('bvms_branch_referral')
    with op.batch_alter_table('bvms_case', schema=None) as batch_op:
        batch_op.drop_index('ix_bvms_case_ward_status')
        batch_op.drop_index('ix_bvms_case_status_zone')
        batch_op.drop_index(batch_op.f('ix_bvms_case_status'))
        batch_op.drop_index('ix_bvms_case_response_due')
        batch_op.drop_index(batch_op.f('ix_bvms_case_pid'))
        batch_op.drop_index(batch_op.f('ix_bvms_case_litigation_status'))
        batch_op.drop_index('ix_bvms_case_land_type')
        batch_op.drop_index(batch_op.f('ix_bvms_case_created_at'))
        batch_op.drop_index('ix_bvms_case_compliance_due')
        batch_op.drop_index(batch_op.f('ix_bvms_case_case_no'))

    op.drop_table('bvms_case')
    with op.batch_alter_table('bvms_sanctioned_plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_sanctioned_plan_pid'))

    op.drop_table('bvms_sanctioned_plan')
    op.drop_table('bvms_officer_profile_wards')
    with op.batch_alter_table('bvms_inspection_task', schema=None) as batch_op:
        batch_op.drop_index('ix_bvms_task_status_zone')
        batch_op.drop_index('ix_bvms_task_assigned_status')
        batch_op.drop_index(batch_op.f('ix_bvms_inspection_task_status'))
        batch_op.drop_index(batch_op.f('ix_bvms_inspection_task_pid'))
        batch_op.drop_index(batch_op.f('ix_bvms_inspection_task_created_at'))

    op.drop_table('bvms_inspection_task')
    with op.batch_alter_table('bvms_govt_land_parcel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_govt_land_parcel_layer_key'))

    op.drop_table('bvms_govt_land_parcel')
    op.drop_table('bvms_ward')
    op.drop_table('bvms_officer_profile_zones')
    op.drop_table('bvms_officer_profile_divisions')
    op.drop_table('bvms_officer_permission_override')
    op.drop_table('bvms_workflow_setting')
    op.drop_table('bvms_workflow_rule')
    op.drop_table('bvms_role_permission')
    with op.batch_alter_table('bvms_officer_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_officer_profile_mobile'))

    op.drop_table('bvms_officer_profile')
    op.drop_table('bvms_legal_section')
    op.drop_table('bvms_legacy_batch')
    with op.batch_alter_table('bvms_land_layer_upload', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_land_layer_upload_layer_key'))

    op.drop_table('bvms_land_layer_upload')
    op.drop_table('bvms_integrity_nonce')
    op.drop_table('bvms_inspection_batch')
    op.drop_table('bvms_division')
    op.drop_table('bvms_app_attest_key')
    with op.batch_alter_table('bvms_admin_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_admin_audit_log_at'))

    op.drop_table('bvms_admin_audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('bvms_zone')
    op.drop_table('bvms_violation_type')
    op.drop_table('bvms_sla_config')
    op.drop_table('bvms_sequence')
    with op.batch_alter_table('bvms_otp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bvms_otp_mobile'))

    op.drop_table('bvms_otp')
    op.drop_table('bvms_order_type')
    op.drop_table('bvms_legal_statute')
    op.drop_table('bvms_branch')
    # ### end Alembic commands ###
