"""case occupancy head counts

Revision ID: fd9465cee474
Revises: 2eb08428ec2a
Create Date: 2026-09-21 22:39:30.776410
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = 'fd9465cee474'
down_revision = '2eb08428ec2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bvms_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupants_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occupants_senior_citizens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occupants_children', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('occupants_women', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bvms_case', schema=None) as batch_op:
        batch_op.drop_column('occupants_women')
        batch_op.drop_column('occupants_children')
        batch_op.drop_column('occupants_senior_citizens')
        batch_op.drop_column('occupants_total')

    # ### end Alembic commands ###
