# Generated by Django 5.2.17 on 2026-09-11 06:48

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('building_violations', '0003_alter_landlayerupload_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaattachment',
            name='integrity_status',
            field=models.CharField(db_index=True, default='UNVERIFIED', max_length=12),
        ),
        migrations.CreateModel(
            name='AppAttestKey',
            fields=[
                ('key_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('public_key_pem', models.TextField()),
                ('counter', models.PositiveBigIntegerField(default=0)),
                ('environment', models.CharField(default='production', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_app_attest_key',
            },
        ),
        migrations.CreateModel(
            name='IntegrityNonce',
            fields=[
                ('nonce', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bvms_integrity_nonce',
            },
        ),
        migrations.CreateModel(
            name='LocationIntegrityCheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('context', models.CharField(choices=[('PRECHECK', 'Pre-check'), ('MEDIA_UPLOAD', 'Evidence upload'), ('CASE_CREATE', 'Inspection recorded'), ('TASK_START', 'Planned inspection started'), ('TASK_CLOSE', 'Planned inspection closed')], max_length=14)),
                ('decision', models.CharField(choices=[('PASS', 'Pass'), ('FLAGGED', 'Flagged'), ('REJECTED', 'Rejected')], db_index=True, max_length=10)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('flags', models.JSONField(blank=True, default=list)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('accuracy_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('altitude_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('speed_mps', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('provider', models.CharField(blank=True, max_length=30)),
                ('fix_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('fix_age_s', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('jitter_m', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('device_id', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(blank=True, max_length=10)),
                ('source', models.CharField(blank=True, max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('build_number', models.CharField(blank=True, max_length=40)),
                ('os_version', models.CharField(blank=True, max_length=40)),
                ('device_model', models.CharField(blank=True, max_length=80)),
                ('native_module', models.BooleanField(default=False)),
                ('is_physical_device', models.BooleanField(blank=True, null=True)),
                ('mock_location', models.BooleanField(blank=True, null=True)),
                ('rooted', models.BooleanField(blank=True, null=True)),
                ('developer_options', models.BooleanField(blank=True, null=True)),
                ('vpn_active', models.BooleanField(blank=True, null=True)),
                ('proxy_configured', models.BooleanField(blank=True, null=True)),
                ('simulated_by_software', models.BooleanField(blank=True, null=True)),
                ('produced_by_accessory', models.BooleanField(blank=True, null=True)),
                ('attestation_type', models.CharField(blank=True, max_length=20)),
                ('attestation_status', models.CharField(default='NONE', max_length=12)),
                ('attestation_detail', models.JSONField(blank=True, default=dict)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_intel', models.JSONField(blank=True, default=dict)),
                ('ip_distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True)),
                ('travel_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('travel_speed_kmph', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('signals', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_checks', to='building_violations.violationcase')),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='building_violations.mediaattachment')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='building_violations.locationintegritycheck')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrity_checks', to='building_violations.inspectiontask')),
            ],
            options={
                'db_table': 'bvms_location_integrity',
                'ordering': ['-at'],
            },
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='integrity_check',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='building_violations.locationintegritycheck'),
        ),
        migrations.AddIndex(
            model_name='locationintegritycheck',
            index=models.Index(fields=['officer', 'at'], name='bvms_locati_officer_47d2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='locationintegritycheck',
            index=models.Index(fields=['decision', 'at'], name='bvms_locati_decisio_9b2f59_idx'),
        ),
    ]
