import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Download, FileSignature, Gavel, History, Lock, MessageSquareReply, OctagonPause, RefreshCw, ShieldCheck, Smartphone, XCircle } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useNavigate, useParams } from "react-router-dom";
import { cases, masters, notices as noticesApi } from "@/api/endpoints";
import { errorMessage } from "@/api/client";
import type { CaseDetail, Media, Notice } from "@/api/types";
import MapView from "@/components/MapView";
import MediaGallery from "@/components/MediaGallery";
import Uploader from "@/components/Uploader";
import { Alert, Card, Field, LandBadge, Modal, SeverityBadge, Spinner, StatusBadge } from "@/components/ui";
import { daysLeft, fmtDate, fmtDateTime, inr } from "@/utils/format";
import { useAuth } from "@/store/auth";

type ModalKind = null | "submit_to_ae" | "ae_forward" | "ae_return" | "issue_notice" | "issue_order" | "record_service" | "record_response" | "ae_forward_response" | "schedule_hearing" | "record_hearing" | "drop" | "regularise" | "record_appeal" | "decide_appeal" | "record_execution" | "close" | "reopen";
const LABELS: Record<string, { label: string; icon: any; cls: string }> = {
  submit_to_ae: { label: "Submit to AE", icon: CheckCircle2, cls: "btn-primary" }, ae_forward: { label: "Forward to JC", icon: CheckCircle2, cls: "btn-primary" }, ae_return: { label: "Return to JE", icon: XCircle, cls: "btn-outline" },
  issue_notice: { label: "Issue notice / SCN", icon: FileSignature, cls: "btn-primary" }, issue_order: { label: "Pass final order", icon: Gavel, cls: "btn-danger" }, record_service: { label: "Record delivery of notice/order", icon: Smartphone, cls: "btn-accent" },
  record_response: { label: "Upload reply of noticee", icon: MessageSquareReply, cls: "btn-accent" }, ae_forward_response: { label: "Comment & forward reply", icon: CheckCircle2, cls: "btn-primary" }, schedule_hearing: { label: "Fix hearing", icon: History, cls: "btn-outline" },
  record_hearing: { label: "Record hearing", icon: History, cls: "btn-outline" }, drop: { label: "Drop case", icon: XCircle, cls: "btn-outline" }, regularise: { label: "Regularise / compound", icon: ShieldCheck, cls: "btn-outline" },
  record_appeal: { label: "Record appeal / stay", icon: Gavel, cls: "btn-outline" }, decide_appeal: { label: "Record appeal decision", icon: Gavel, cls: "btn-outline" }, record_execution: { label: "Record demolition / sealing", icon: Lock, cls: "btn-danger" },
  close: { label: "Verify & close", icon: CheckCircle2, cls: "btn-primary" }, reopen: { label: "Reopen", icon: RefreshCw, cls: "btn-outline" }, update: { label: "Edit", icon: RefreshCw, cls: "btn-outline" }, add_media: { label: "Add evidence", icon: Smartphone, cls: "btn-outline" },
};

export default function CaseDetailPage() {
  const { id } = useParams();
  const { t } = useTranslation();
  const nav = useNavigate();
  const qc = useQueryClient();
  const user = useAuth((s) => s.user);
  const q = useQuery({ queryKey: ["case", id], queryFn: () => cases.get(id!) });
  const [modal, setModal] = useState<ModalKind>(null);
  const [tab, setTab] = useState<"overview" | "evidence" | "notices" | "proceedings" | "timeline">("overview");
  const [err, setErr] = useState("");
  const act = useMutation({ mutationFn: ({ action, data }: { action: string; data: Record<string, unknown> }) => cases.action(id!, action, data), onSuccess: () => { qc.invalidateQueries({ queryKey: ["case", id] }); qc.invalidateQueries({ queryKey: ["counts"] }); setModal(null); setErr(""); }, onError: (e) => setErr(errorMessage(e)) });
  if (q.isLoading || !q.data) return <Spinner />;
  const c = q.data;
  const actions = c.available_actions.filter((a) => a !== "add_media");
  const onAction = (a: string) => { if (a === "update") nav(`/cases/${id}/edit`); else if (a === "submit_to_ae") act.mutate({ action: "submit", data: {} }); else setModal(a as ModalKind); };
  const primary = c.violations.find((v) => v.is_primary) || c.violations[0];
  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-start gap-3">
        <div className="flex-1 min-w-[260px]">
          <div className="flex items-center gap-2 flex-wrap"><h1 className="page-title font-mono">{c.case_no}</h1><StatusBadge status={c.status} /><LandBadge land={c.land_type} />{c.stop_work_issued && <span className="badge bg-danger-50 text-danger-600"><OctagonPause className="h-3 w-3 mr-1" />Stop-work</span>}{c.sealed && <span className="badge bg-warning-50 text-warning-600"><Lock className="h-3 w-3 mr-1" />Sealed</span>}{c.sla_breached && <span className="badge bg-danger-500 text-white">SLA breached</span>}</div>
          <p className="page-sub">{c.address_line}{c.locality && `, ${c.locality}`} · Zone {c.zone_code ?? "-"} / Ward {c.ward_number ?? "-"}{c.pid && <> · PID <b>{c.pid}</b></>} · with <b>{c.current_owner_role}</b></p>
        </div>
        <div className="flex flex-wrap gap-2">{actions.map((a) => { const L = LABELS[a] || { label: a, icon: CheckCircle2, cls: "btn-outline" }; return <button key={a} className={L.cls} onClick={() => onAction(a)}><L.icon className="h-4 w-4" />{L.label}</button>; })}</div>
      </div>
      {err && <Alert kind="error">{err}</Alert>}
      <Clock c={c} />
      <div className="flex gap-1 border-b border-light-border">{(["overview", "evidence", "notices", "proceedings", "timeline"] as const).map((k) => <button key={k} className={`px-4 py-2 text-sm font-medium border-b-2 -mb-px ${tab === k ? "border-primary-500 text-primary-700" : "border-transparent text-light-text-muted hover:text-light-text"}`} onClick={() => setTab(k)}>{k[0].toUpperCase() + k.slice(1)}{k === "notices" ? ` (${c.notices.length})` : k === "evidence" ? ` (${c.media.length})` : ""}</button>)}</div>
      {tab === "overview" && (
        <div className="grid lg:grid-cols-3 gap-4">
          <Card title="Violations" className="lg:col-span-2">
            <div className="space-y-2">{c.violations.map((v) => <div key={v.id} className="rounded-lg border border-light-border p-3 text-sm"><div className="flex items-center gap-2 flex-wrap"><span className="font-mono text-xs text-primary-600">{v.code}</span><span className="font-medium">{v.violation_type.title_en}</span><SeverityBadge s={v.violation_type.severity} />{v.is_primary && <span className="badge bg-primary-500 text-white">primary</span>}</div><div className="text-xs text-light-text-muted">{v.violation_type.title_hi}</div><div className="text-xs mt-1"><b>Contravention of:</b> {v.violation_type.contravention_of}</div>{(v.details as any)?.permitted && <div className="text-xs">Permitted: {(v.details as any).permitted} · Actual: {(v.details as any).actual}</div>}{v.remarks && <div className="text-xs">Remarks: {v.remarks}</div>}<div className="text-[11px] text-light-text-muted mt-1">Action path {v.violation_type.action_path} · SCN {v.violation_type.scn_response_days_default} d · order {v.violation_type.order_compliance_days_default} d (min {v.violation_type.statutory_minimum_days}) · fine {v.violation_type.schedule_fine_inr ? inr(v.violation_type.schedule_fine_inr) : "-"}{v.violation_type.schedule_daily_fine_inr ? ` + ${inr(v.violation_type.schedule_daily_fine_inr)}/day` : ""}</div></div>)}</div>
            <div className="mt-4"><div className="label">Inspection report</div><p className="text-sm whitespace-pre-wrap">{c.description}</p>{Object.keys(c.measurements || {}).length > 0 && <div className="text-xs text-light-text-muted mt-1">{Object.entries(c.measurements).map(([k, v]) => `${k}: ${v}`).join(" · ")}</div>}</div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mt-4 text-sm">
              {[["Owner", c.owner_name || "-"], ["Father/husband", c.owner_father_name || "-"], ["Occupier / builder", c.occupier_name || c.builder_name || "-"], ["On site", c.person_on_site || "-"], ["PID mobile", c.pid_linked_mobile || "-"], ["Alternate mobile", c.alternate_mobile || "-"], ["Stage", c.construction_stage], ["Storeys / height", `${c.storeys || "-"} / ${c.height_m ? c.height_m + " m" : "-"}`], ["Plot / covered", `${c.plot_area_sqm || "-"} / ${c.covered_area_sqm || "-"} sq m`], ["Use observed", c.use_observed || "-"], ["Source", `${c.source}${c.complaint_ref ? " " + c.complaint_ref : ""}`], ["Inspected", fmtDateTime(c.inspected_at)]].map(([k, v]) => <div key={k}><div className="label">{k}</div><div>{v}</div></div>)}
            </div>
            {c.decision && <div className="mt-4 rounded-lg bg-primary-50 border border-primary-100 p-3 text-sm"><div className="font-semibold">Decision: {c.decision} ({fmtDate(c.decided_at)})</div><div className="whitespace-pre-wrap">{c.decision_reasons}</div>{c.demolition_cost_inr && <div className="text-xs mt-1">Demolition cost {inr(c.demolition_cost_inr)} · recovery {c.cost_recovery_status}</div>}</div>}
          </Card>
          <div className="space-y-4">
            <Card title="Location">{c.latitude ? <MapView height="220px" marker={[Number(c.latitude), Number(c.longitude)]} govtLand={c.govt_parcel ? { type: "FeatureCollection", features: [{ type: "Feature", geometry: c.govt_parcel.geometry, properties: c.govt_parcel }] } : undefined} /> : <div className="text-sm text-light-text-muted">No coordinates</div>}{c.govt_parcel && <div className="text-xs mt-2 text-danger-700">Inside {c.govt_parcel.agency} land: {c.govt_parcel.name || c.govt_parcel.khasra_no} ({c.govt_parcel.land_use})</div>}</Card>
            <Card title="Sanctioned plan">{c.sanctioned_plan ? <div className="text-sm space-y-1"><div className="font-mono text-xs">{c.sanctioned_plan.plan_no}</div><div>{fmtDate(c.sanctioned_plan.sanctioned_on)} → {fmtDate(c.sanctioned_plan.valid_till)} · {c.sanctioned_plan.sanction_mode}</div><div>Floors {c.sanctioned_plan.permitted_floors} · coverage {c.sanctioned_plan.permitted_ground_coverage_pct}% · FAR {c.sanctioned_plan.permitted_far} · height {c.sanctioned_plan.permitted_height_m} m</div>{c.sanctioned_plan.licence_no && <div>Licence {c.sanctioned_plan.licence_no} ({c.sanctioned_plan.licence_authority}) - {c.sanctioned_plan.licence_holder}</div>}<div className="text-xs text-light-text-muted">Architect {c.sanctioned_plan.architect_name || "-"}</div></div> : <div className="text-sm text-light-text-muted">No sanctioned plan on record for this PID {["JE", "AE", "ADMIN"].includes(user?.role || "") && <button className="text-primary-600 underline" onClick={() => nav("/plans")}>add</button>}</div>}</Card>
            <Card title="People"><div className="text-sm space-y-1"><div><span className="label inline">JE</span> {c.reported_by?.name}</div><div><span className="label inline">AE</span> {c.assigned_ae?.name || "-"}</div><div><span className="label inline">JC</span> {c.assigned_jc?.name || "-"}</div></div></Card>
          </div>
        </div>
      )}
      {tab === "evidence" && <div className="space-y-4">{["INSPECTION", "NOTICE_DELIVERY", "ORDER_DELIVERY", "RESPONSE", "HEARING", "EXECUTION", "COMPLIANCE", "APPEAL", "OTHER"].map((k) => c.media.some((m) => m.kind === k) && <Card key={k} title={k.replace(/_/g, " ")}><MediaGallery items={c.media} kind={k} /></Card>)}<Card title="Add evidence"><Uploader caseId={c.id} kind="OTHER" onUploaded={() => qc.invalidateQueries({ queryKey: ["case", id] })} /></Card></div>}
      {tab === "notices" && <div className="space-y-3">{c.notices.length ? c.notices.map((n) => <NoticeCard key={n.id} n={n} onChanged={() => qc.invalidateQueries({ queryKey: ["case", id] })} />) : <Card><div className="text-sm text-light-text-muted">No notice issued yet.</div></Card>}</div>}
      {tab === "proceedings" && (
        <div className="grid lg:grid-cols-2 gap-4">
          <Card title="Replies of noticee">{c.responses.length ? c.responses.map((r) => <div key={r.id} className="border-b border-light-border py-2 text-sm"><div className="flex justify-between"><b>{fmtDate(r.received_on)} via {r.received_via}</b><span className={`badge ${r.is_within_time ? "bg-success-50 text-success-700" : "bg-danger-50 text-danger-600"}`}>{r.is_within_time ? "in time" : "late"}</span></div><div className="whitespace-pre-wrap">{r.summary}</div>{r.requests_hearing && <div className="text-xs text-primary-600">Hearing requested</div>}{r.ae_comments && <div className="text-xs mt-1 bg-gray-50 rounded p-2"><b>AE:</b> {r.ae_comments}</div>}</div>) : <div className="text-sm text-light-text-muted">None</div>}</Card>
          <Card title="Hearings">{c.hearings.length ? c.hearings.map((h) => <div key={h.id} className="border-b border-light-border py-2 text-sm"><b>{fmtDateTime(h.scheduled_at)}</b> · {h.venue} · {h.presiding?.name}<div className="text-xs">{h.held_at ? `${h.outcome} on ${fmtDateTime(h.held_at)}` : "pending"}{h.next_date && ` · next ${fmtDateTime(h.next_date)}`}</div>{h.proceedings && <div className="text-xs whitespace-pre-wrap mt-1">{h.proceedings}</div>}</div>) : <div className="text-sm text-light-text-muted">None</div>}</Card>
          <Card title="Appeals">{c.appeals.length ? c.appeals.map((a) => <div key={a.id} className="border-b border-light-border py-2 text-sm"><b>{a.authority}</b> · filed {fmtDate(a.filed_on)} · {a.appeal_no || "-"} · <span className="badge bg-gray-100">{a.status}</span>{a.stay_granted && <div className="text-xs text-danger-600">Stay till {fmtDate(a.stay_until)} · {a.conditions}</div>}{a.decision_summary && <div className="text-xs">{fmtDate(a.decided_on)}: {a.decision_summary}</div>}</div>) : <div className="text-sm text-light-text-muted">None</div>}</Card>
          <Card title="Execution / compliance">{c.executions.length ? c.executions.map((e) => <div key={e.id} className="border-b border-light-border py-2 text-sm"><b>{e.action}</b> · {e.mode} · {fmtDateTime(e.executed_on)}<div className="text-xs">{e.squad_incharge && `Squad: ${e.squad_incharge} · `}{e.police_assistance && `Police ${e.police_station} · `}{e.duty_magistrate && `DM ${e.duty_magistrate} · `}{e.area_demolished_sqm && `${e.area_demolished_sqm} sq m · `}{e.seal_memo_no && `Seal memo ${e.seal_memo_no} · `}{e.cost_incurred_inr && `cost ${inr(e.cost_incurred_inr)}`}</div>{e.remarks && <div className="text-xs">{e.remarks}</div>}<div className="text-xs text-light-text-muted">by {e.recorded_by?.name}{e.verified_by && ` · verified by ${e.verified_by.name}`}</div></div>) : <div className="text-sm text-light-text-muted">None</div>}</Card>
        </div>
      )}
      {tab === "timeline" && <Timeline id={c.id} events={c.events} />}
      <ActionModal kind={modal} c={c} onClose={() => setModal(null)} onSubmit={(action, data) => act.mutate({ action, data })} busy={act.isPending} err={err} />
    </div>
  );
}

function Clock({ c }: { c: CaseDetail }) {
  const items: { label: string; at: string | null; strong?: boolean }[] = [{ label: "Inspected", at: c.inspected_at }, { label: "Submitted", at: c.submitted_at }, { label: "AE forwarded", at: c.ae_forwarded_at }, { label: "SCN issued", at: c.scn_issued_at }, { label: "SCN served", at: c.scn_served_at }, { label: "Reply due", at: c.response_due_at, strong: true }, { label: "Reply received", at: c.response_received_at }, { label: "Hearing", at: c.hearing_at }, { label: "Decided", at: c.decided_at }, { label: "Order served", at: c.order_served_at }, { label: "Comply by", at: c.compliance_due_at, strong: true }, { label: "Executed", at: c.executed_at }, { label: "Closed", at: c.closed_at }];
  const dl = c.status === "ORDER_SERVED" ? daysLeft(c.compliance_due_at) : c.status === "SCN_SERVED" ? daysLeft(c.response_due_at) : null;
  return (
    <div className="card p-3 flex flex-wrap gap-x-5 gap-y-1 text-xs items-center">
      {items.filter((i) => i.at).map((i) => <div key={i.label}><span className="text-light-text-muted">{i.label}</span> <b className={i.strong ? "text-danger-600" : ""}>{fmtDate(i.at)}</b></div>)}
      {dl != null && <div className={`ml-auto badge ${dl < 0 ? "bg-danger-500 text-white" : dl <= 3 ? "bg-warning-100 text-warning-600" : "bg-accent-100 text-accent-700"}`}>{dl < 0 ? `${-dl} days overdue` : `${dl} days left`}</div>}
      {c.stage_due_at && !["CLOSED", "DROPPED", "REGULARISED"].includes(c.status) && <div className={`badge ${new Date(c.stage_due_at) < new Date() ? "bg-danger-50 text-danger-600" : "bg-gray-100"}`}>SLA {fmtDateTime(c.stage_due_at)}</div>}
    </div>
  );
}

function NoticeCard({ n, onChanged }: { n: Notice; onChanged: () => void }) {
  const [busy, setBusy] = useState(false);
  const resend = async () => { setBusy(true); try { await noticesApi.resendSms(n.id); onChanged(); } finally { setBusy(false); } };
  return (
    <div className="card p-4 text-sm">
      <div className="flex flex-wrap items-center gap-2"><span className={`badge ${n.kind === "ORDER" ? "bg-danger-50 text-danger-600" : n.kind === "NOTICE" ? "bg-primary-50 text-primary-700" : "bg-gray-100"}`}>{n.kind}</span><b className="font-mono">{n.notice_no}</b><span>{n.order_type.title_en}</span>{n.is_final_order && <span className="badge bg-danger-500 text-white">final order</span>}<span className="ml-auto text-xs text-light-text-muted">{fmtDateTime(n.issued_at)} · {n.issued_by?.name}</span></div>
      <div className="grid md:grid-cols-4 gap-2 mt-2 text-xs">
        <div><div className="label">Addressee</div>{n.addressee_name}<div className="text-light-text-muted">{n.addressee_mobiles.join(", ") || "no mobile"}</div></div>
        <div><div className="label">Periods</div>{n.response_days ? `Reply in ${n.response_days} d (${fmtDate(n.response_due_at)})` : ""}{n.compliance_days ? `Comply in ${n.compliance_days} d (${fmtDate(n.compliance_due_at)})` : ""}{n.hearing_at && <div>Hearing {fmtDateTime(n.hearing_at)}</div>}</div>
        <div><div className="label">Signature</div>{n.signature_status === "SIGNED" ? <span className="text-success-700 flex items-center gap-1"><ShieldCheck className="h-3 w-3" />{n.signer_name}</span> : <span className="text-danger-600">{n.signature_status}{n.signature_error && `: ${n.signature_error.slice(0, 80)}`}</span>}<div className="text-light-text-muted">Verify {n.verification_code}</div></div>
        <div><div className="label">Service</div>{n.served_at ? <span className="text-success-700">{n.served_mode} on {fmtDate(n.served_at)} by {n.served_by?.name}</span> : <span className="text-warning-600">not yet served</span>}<div className="text-light-text-muted">SMS: {n.dispatches.map((d) => `${d.to} ${d.status}`).join("; ") || "-"}</div></div>
      </div>
      {n.delivery_media.length > 0 && <div className="mt-2"><MediaGallery items={n.delivery_media} /></div>}
      <div className="flex gap-2 mt-3"><a className="btn-primary" href={noticesApi.pdfUrl(n.id)} target="_blank" rel="noreferrer" onClick={(e) => { e.preventDefault(); openPdf(n.id); }}><Download className="h-4 w-4" />Download / print PDF</a><button className="btn-outline" disabled={busy} onClick={resend}><Smartphone className="h-4 w-4" />Resend SMS</button>{n.signature_status !== "SIGNED" && <button className="btn-outline" onClick={() => noticesApi.resign(n.id).then(onChanged)}>Retry signing</button>}</div>
    </div>
  );
}

async function openPdf(id: string) {
  const { api } = await import("@/api/client");
  const r = await api.get(`/notices/${id}/pdf/`, { responseType: "blob" });
  window.open(URL.createObjectURL(r.data), "_blank");
}

function Timeline({ id, events }: { id: string; events: CaseDetail["events"] }) {
  const q = useQuery({ queryKey: ["timeline", id], queryFn: () => cases.timeline(id) });
  return (
    <Card title="Audit trail (hash-chained)" actions={q.data && <span className={`badge ${q.data.chain.ok ? "bg-success-50 text-success-700" : "bg-danger-500 text-white"}`}>{q.data.chain.ok ? `chain intact · ${q.data.chain.events} events` : `CHAIN BROKEN at #${q.data.chain.broken_at_event_id}`}</span>}>
      <ol className="relative border-l border-light-border ml-2">{events.map((e) => <li key={e.id} className="ml-4 pb-4"><span className="absolute -left-1.5 h-3 w-3 rounded-full bg-primary-500 border-2 border-white" /><div className="text-sm"><b>{e.action.replace(/_/g, " ")}</b>{e.to_status && e.to_status !== e.from_status && <> → <StatusBadge status={e.to_status} /></>}</div><div className="text-xs text-light-text-muted">{fmtDateTime(e.at)} · {e.actor?.name || "system"} ({e.actor_role || "-"}){e.latitude && ` · ${Number(e.latitude).toFixed(5)}, ${Number(e.longitude).toFixed(5)}`}</div>{e.remarks && <div className="text-xs whitespace-pre-wrap">{e.remarks}</div>}<div className="text-[10px] font-mono text-gray-400 truncate">{e.hash}</div></li>)}</ol>
    </Card>
  );
}

function ActionModal({ kind, c, onClose, onSubmit, busy, err }: { kind: ModalKind; c: CaseDetail; onClose: () => void; onSubmit: (action: string, data: Record<string, unknown>) => void; busy: boolean; err: string }) {
  const [f, setF] = useState<Record<string, any>>({});
  const [media, setMedia] = useState<Media[]>([]);
  const officers = useQuery({ queryKey: ["officers", "JC", c.zone], queryFn: () => masters.officers({ role: "JC", zone: c.zone ?? "" }), enabled: kind === "ae_forward" });
  if (!kind) return null;
  const set = (k: string, v: any) => setF((s) => ({ ...s, [k]: v }));
  const close = () => { setF({}); setMedia([]); onClose(); };
  const mids = media.map((m) => m.id);
  const scnNotice = c.notices.find((n) => n.kind === "NOTICE" && !n.served_at) || c.notices.find((n) => n.kind === "NOTICE");
  const orderNotice = c.notices.find((n) => n.is_final_order && !n.served_at) || c.notices.find((n) => n.is_final_order);
  const orderTypes = c.available_order_types;
  const title = LABELS[kind]?.label || kind;
  const primary = c.violations.find((v) => v.is_primary) || c.violations[0];
  const body = () => {
    switch (kind) {
      case "ae_forward": return <><Field label="Assign to Joint Commissioner"><select className="input" value={f.jc_user || ""} onChange={(e) => set("jc_user", e.target.value ? Number(e.target.value) : null)}><option value="">Auto (JC of the zone)</option>{officers.data?.map((o) => <option key={o.user_id} value={o.user_id}>{o.name} - {o.designation}</option>)}</select></Field><Field label="Recommendation"><select className="input" value={f.recommendation || ""} onChange={(e) => set("recommendation", e.target.value)}><option value="">-</option>{["SCN", "STOP_WORK", "SEALING", "DEMOLITION", "DROP", "REGULARISE", "REFER"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Remarks / verification note"><textarea className="input" rows={3} value={f.remarks || ""} onChange={(e) => set("remarks", e.target.value)} /></Field><Btn onClick={() => onSubmit("ae_forward", f)} /></>;
      case "ae_return": return <><Field label="Reasons for return (mandatory)" required><textarea className="input" rows={3} value={f.remarks || ""} onChange={(e) => set("remarks", e.target.value)} /></Field><Btn disabled={!f.remarks} onClick={() => onSubmit("ae_return", f)} /></>;
      case "issue_notice": case "issue_order": {
        const list = orderTypes.filter((o) => kind === "issue_order" ? o.kind === "ORDER" : o.kind !== "ORDER" || o.code === "STOP_WORK_262" || o.code === "SEALING_263A");
        const ot = list.find((o) => o.code === f.order_type);
        const def = ot ? (ot.kind === "NOTICE" ? Math.max(ot.default_days, primary?.violation_type.scn_response_days_default || 0) : ot.kind === "ORDER" ? Math.max(ot.default_days, primary?.violation_type.order_compliance_days_default || 0) : 0) : 0;
        const isFinal = ot?.kind === "ORDER" && ot.code !== "STOP_WORK_262" && (ot.code !== "SEALING_263A" || kind === "issue_order");
        return <>
          <Field label="Notice / order type" required><select className="input" value={f.order_type || ""} onChange={(e) => { set("order_type", e.target.value); set("days", undefined); }}><option value="">Select…</option>{list.map((o) => <option key={o.code} value={o.code}>{o.title_en} [{o.statute} s.{o.section}]</option>)}</select></Field>
          {ot && <div className="text-xs text-light-text-muted -mt-1">{ot.title_hi} · statutory minimum {ot.min_days} days{ot.appeal_to && ` · appeal: ${ot.appeal_to}${ot.appeal_days ? ` within ${ot.appeal_days} days` : ""}`}</div>}
          {ot && ot.kind !== "MEMO" && ot.kind !== "REFERRAL" && ot.code !== "STOP_WORK_262" && <Field label={ot.kind === "NOTICE" ? "Days to reply" : "Days to comply"} hint={`Default ${def} days; statutory minimum ${ot.min_days}`}><input type="number" className="input" min={ot.min_days} value={f.days ?? def} onChange={(e) => set("days", Number(e.target.value))} /></Field>}
          <div className="grid grid-cols-2 gap-2"><Field label="Addressee name"><input className="input" value={f.addressee_name ?? c.owner_name} onChange={(e) => set("addressee_name", e.target.value)} /></Field><Field label="Additional mobile numbers (comma separated)" hint={`PID-linked ${c.pid_linked_mobile || "-"} and alternate ${c.alternate_mobile || "-"} are included automatically`}><input className="input" value={f.mobiles_text || ""} onChange={(e) => set("mobiles_text", e.target.value)} /></Field></div>
          {ot?.kind === "NOTICE" && <div className="grid grid-cols-2 gap-2"><Field label="Hearing date/time (optional)"><input type="datetime-local" className="input" value={f.hearing_at || ""} onChange={(e) => set("hearing_at", e.target.value)} /></Field><Field label="Hearing venue"><input className="input" value={f.hearing_venue || ""} onChange={(e) => set("hearing_venue", e.target.value)} placeholder="Office of the Joint Commissioner, MCG" /></Field></div>}
          <Field label={isFinal ? "Reasons for the order (speaking order - printed)" : "Operative text / remarks (printed)"}><textarea className="input" rows={4} value={f.remarks || ""} onChange={(e) => set("remarks", e.target.value)} /></Field>
          <label className="text-sm flex items-center gap-2"><input type="checkbox" checked={f.send_sms ?? true} onChange={(e) => set("send_sms", e.target.checked)} />Send SMS to the mobile numbers</label>
          <Alert kind="info">The document will be numbered, rendered bilingually, hashed, digitally signed and a QR code added. It can then be downloaded, printed and served by the field team.</Alert>
          <Btn disabled={!f.order_type || (isFinal && !f.remarks)} label="Issue & sign" onClick={() => onSubmit("issue_notice", { order_type: f.order_type, days: f.days ?? def, addressee_name: f.addressee_name ?? c.owner_name, mobiles: (f.mobiles_text || "").split(",").map((x: string) => x.trim()).filter(Boolean), hearing_at: f.hearing_at || null, hearing_venue: f.hearing_venue || "", operative_text_en: isFinal ? "" : f.remarks || "", remarks: f.remarks || "", send_sms: f.send_sms ?? true, is_final_order: isFinal })} />
        </>;
      }
      case "record_service": { const target = c.status === "ORDER_ISSUED" ? orderNotice : scnNotice; return <>
        <Field label="Notice / order served" required><select className="input" value={f.notice || target?.id || ""} onChange={(e) => set("notice", e.target.value)}>{c.notices.map((n) => <option key={n.id} value={n.id}>{n.notice_no} - {n.order_type.title_en.slice(0, 50)}</option>)}</select></Field>
        <div className="grid grid-cols-2 gap-2"><Field label="Mode of service" required><select className="input" value={f.mode || "AFFIXATION"} onChange={(e) => set("mode", e.target.value)}>{["IN_PERSON", "AFFIXATION", "POST", "SMS", "WHATSAPP", "EMAIL", "BEAT_OF_DRUM"].map((m) => <option key={m}>{m}</option>)}</select></Field><Field label="Served at"><input type="datetime-local" className="input" value={f.served_at || ""} onChange={(e) => set("served_at", e.target.value)} /></Field></div>
        <Field label="Remarks (person who received / refusal / witnesses)"><textarea className="input" rows={2} value={f.remarks || ""} onChange={(e) => set("remarks", e.target.value)} /></Field>
        <Field label="Geotagged proof of delivery (mandatory for affixation)"><Uploader caseId={c.id} kind={c.status === "ORDER_ISSUED" ? "ORDER_DELIVERY" : "NOTICE_DELIVERY"} noticeId={f.notice || target?.id} onUploaded={(m) => setMedia((s) => [...s, m])} requireGeo /></Field><MediaGallery items={media} />
        <Btn disabled={!(f.notice || target)} onClick={() => onSubmit("record_service", { notice: f.notice || target?.id, mode: f.mode || "AFFIXATION", served_at: f.served_at || null, remarks: f.remarks || "", media_ids: mids })} /></>; }
      case "record_response": return <><div className="grid grid-cols-2 gap-2"><Field label="Received on" required><input type="date" className="input" value={f.received_on || ""} onChange={(e) => set("received_on", e.target.value)} /></Field><Field label="Submitted by"><input className="input" value={f.submitted_by_name || ""} onChange={(e) => set("submitted_by_name", e.target.value)} /></Field></div><Field label="Summary of reply" required><textarea className="input" rows={4} value={f.summary || ""} onChange={(e) => set("summary", e.target.value)} /></Field><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={!!f.requests_hearing} onChange={(e) => set("requests_hearing", e.target.checked)} />Noticee requests personal hearing</label><Field label="Scanned reply / documents"><Uploader caseId={c.id} kind="RESPONSE" onUploaded={(m) => setMedia((s) => [...s, m])} /></Field><MediaGallery items={media} /><Btn disabled={!f.received_on || !f.summary} onClick={() => onSubmit("record_response", { ...f, notice: scnNotice?.id || null, media_ids: mids })} /></>;
      case "ae_forward_response": { const r = c.responses[0]; return <><div className="text-sm bg-gray-50 rounded p-2 mb-2">{r?.summary}</div><Field label="AE comments on the reply" required><textarea className="input" rows={4} value={f.comments || ""} onChange={(e) => set("comments", e.target.value)} /></Field><Btn disabled={!f.comments} onClick={() => onSubmit("ae_forward_response", { response: r?.id, comments: f.comments })} /></>; }
      case "schedule_hearing": return <><Field label="Date & time" required><input type="datetime-local" className="input" value={f.scheduled_at || ""} onChange={(e) => set("scheduled_at", e.target.value)} /></Field><Field label="Venue"><input className="input" value={f.venue ?? "Office of the Joint Commissioner, MCG"} onChange={(e) => set("venue", e.target.value)} /></Field><Btn disabled={!f.scheduled_at} onClick={() => onSubmit("schedule_hearing", { ...f, venue: f.venue ?? "Office of the Joint Commissioner, MCG" })} /></>;
      case "record_hearing": { const h = c.hearings.find((x) => !x.held_at) || c.hearings[0]; return <><div className="text-sm">Hearing of {fmtDateTime(h?.scheduled_at)}</div><Field label="Attendees"><input className="input" value={f.attendees || ""} onChange={(e) => set("attendees", e.target.value)} /></Field><Field label="Proceedings" required><textarea className="input" rows={4} value={f.proceedings || ""} onChange={(e) => set("proceedings", e.target.value)} /></Field><div className="grid grid-cols-2 gap-2"><Field label="Outcome"><select className="input" value={f.outcome || "HEARD"} onChange={(e) => set("outcome", e.target.value)}>{["HEARD", "ADJOURNED", "EX_PARTE"].map((x) => <option key={x}>{x}</option>)}</select></Field>{f.outcome === "ADJOURNED" && <Field label="Next date"><input type="datetime-local" className="input" value={f.next_date || ""} onChange={(e) => set("next_date", e.target.value)} /></Field>}</div><Btn disabled={!f.proceedings} onClick={() => onSubmit("record_hearing", { hearing: h?.id, proceedings: f.proceedings, attendees: f.attendees || "", outcome: f.outcome || "HEARD", next_date: f.next_date || null, media_ids: mids })} /></>; }
      case "drop": case "regularise": return <><Alert kind="warning">{kind === "drop" ? "Dropping requires a speaking order recorded here; the case will be closed as 'no violation / not pressed'." : "Use only where the construction has been brought into conformity or compounded under the Haryana Building Code, 2017 with composition charges paid."}</Alert><Field label="Reasons (speaking order)" required><textarea className="input" rows={4} value={f.remarks || ""} onChange={(e) => set("remarks", e.target.value)} /></Field><Btn disabled={!f.remarks} onClick={() => onSubmit("drop", { remarks: f.remarks, regularised: kind === "regularise" })} /></>;
      case "record_appeal": return <><div className="grid grid-cols-2 gap-2"><Field label="Filed on" required><input type="date" className="input" value={f.filed_on || ""} onChange={(e) => set("filed_on", e.target.value)} /></Field><Field label="Authority" required><select className="input" value={f.authority || ""} onChange={(e) => set("authority", e.target.value)}><option value="">-</option>{["Divisional Commissioner, Gurugram", "Commissioner, MCG", "Punjab & Haryana High Court", "Civil Court", "Other"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Appeal / case no."><input className="input" value={f.appeal_no || ""} onChange={(e) => set("appeal_no", e.target.value)} /></Field><Field label="Stay until"><input type="date" className="input" value={f.stay_until || ""} onChange={(e) => set("stay_until", e.target.value)} /></Field></div><label className="text-sm flex items-center gap-2"><input type="checkbox" checked={!!f.stay_granted} onChange={(e) => set("stay_granted", e.target.checked)} />Stay granted (pauses the compliance clock)</label><Field label="Conditions (e.g. bank guarantee u/s 263A(4))"><textarea className="input" rows={2} value={f.conditions || ""} onChange={(e) => set("conditions", e.target.value)} /></Field><Field label="Order copy"><Uploader caseId={c.id} kind="APPEAL" onUploaded={(m) => setMedia((s) => [...s, m])} /></Field><Btn disabled={!f.filed_on || !f.authority} onClick={() => onSubmit("record_appeal", { ...f, stay_until: f.stay_until || null, media_ids: mids })} /></>;
      case "decide_appeal": { const a = c.appeals.find((x) => x.status === "STAYED" || x.status === "PENDING") || c.appeals[0]; return <><div className="text-sm">{a?.authority} · {a?.appeal_no}</div><div className="grid grid-cols-2 gap-2"><Field label="Outcome" required><select className="input" value={f.status || ""} onChange={(e) => set("status", e.target.value)}><option value="">-</option>{["DISMISSED", "ALLOWED", "MODIFIED", "WITHDRAWN", "STAYED", "PENDING"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Decided on" required><input type="date" className="input" value={f.decided_on || ""} onChange={(e) => set("decided_on", e.target.value)} /></Field><Field label="Fresh compliance days (if modified)"><input type="number" className="input" value={f.new_compliance_days || ""} onChange={(e) => set("new_compliance_days", e.target.value ? Number(e.target.value) : null)} /></Field></div><Field label="Summary of the appellate order"><textarea className="input" rows={3} value={f.decision_summary || ""} onChange={(e) => set("decision_summary", e.target.value)} /></Field><Btn disabled={!f.status || !f.decided_on} onClick={() => onSubmit("decide_appeal", { appeal: a?.id, ...f, media_ids: mids })} /></>; }
      case "record_execution": return <><div className="grid grid-cols-2 gap-2"><Field label="Action" required><select className="input" value={f.action || "DEMOLITION"} onChange={(e) => set("action", e.target.value)}>{["DEMOLITION", "PARTIAL_DEMOLITION", "SEALING", "DESEALING", "EVICTION", "REMOVAL", "ALTERATION"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Carried out by" required><select className="input" value={f.mode || "CORPORATION"} onChange={(e) => set("mode", e.target.value)}><option value="CORPORATION">Corporation (enforcement squad)</option><option value="OWNER_SELF">Owner (self-compliance)</option></select></Field><Field label="Executed on" required><input type="datetime-local" className="input" value={f.executed_on || ""} onChange={(e) => set("executed_on", e.target.value)} /></Field><Field label="Squad in-charge"><input className="input" value={f.squad_incharge || ""} onChange={(e) => set("squad_incharge", e.target.value)} /></Field><Field label="Police station (if assistance)"><input className="input" value={f.police_station || ""} onChange={(e) => { set("police_station", e.target.value); set("police_assistance", !!e.target.value); }} /></Field><Field label="Duty magistrate"><input className="input" value={f.duty_magistrate || ""} onChange={(e) => set("duty_magistrate", e.target.value)} /></Field><Field label="Machinery used"><input className="input" value={f.machinery_used || ""} onChange={(e) => set("machinery_used", e.target.value)} /></Field><Field label="Area demolished (sq m)"><input className="input" value={f.area_demolished_sqm || ""} onChange={(e) => set("area_demolished_sqm", e.target.value)} /></Field><Field label="Seal memo no."><input className="input" value={f.seal_memo_no || ""} onChange={(e) => set("seal_memo_no", e.target.value)} /></Field><Field label="Cost incurred (INR, recoverable)"><input className="input" value={f.cost_incurred_inr || ""} onChange={(e) => set("cost_incurred_inr", e.target.value)} /></Field></div><Field label="Remarks"><textarea className="input" rows={2} value={f.remarks || ""} onChange={(e) => set("remarks", e.target.value)} /></Field><Field label="Geotagged photos / videos of the demolition or sealing (mandatory)"><Uploader caseId={c.id} kind={f.mode === "OWNER_SELF" ? "COMPLIANCE" : "EXECUTION"} onUploaded={(m) => setMedia((s) => [...s, m])} requireGeo /></Field><MediaGallery items={media} /><Btn disabled={!f.executed_on || !mids.length} onClick={() => onSubmit("record_execution", { action: f.action || "DEMOLITION", mode: f.mode || "CORPORATION", executed_on: f.executed_on, media_ids: mids, squad_incharge: f.squad_incharge || "", police_assistance: !!f.police_assistance, police_station: f.police_station || "", duty_magistrate: f.duty_magistrate || "", machinery_used: f.machinery_used || "", area_demolished_sqm: f.area_demolished_sqm || null, seal_memo_no: f.seal_memo_no || "", cost_incurred_inr: f.cost_incurred_inr || null, remarks: f.remarks || "" })} /></>;
      case "close": case "reopen": return <><Field label="Remarks" required={kind === "reopen"}><textarea className="input" rows={3} value={f.remarks || ""} onChange={(e) => set("remarks", e.target.value)} /></Field><Btn disabled={kind === "reopen" && !f.remarks} onClick={() => onSubmit(kind, f)} /></>;
      default: return null;
    }
  };
  function Btn({ onClick, disabled, label }: { onClick: () => void; disabled?: boolean; label?: string }) { return <div className="flex justify-end gap-2 pt-2">{err && <span className="text-sm text-danger-600 flex-1">{err}</span>}<button className="btn-outline" onClick={close}>Cancel</button><button className="btn-primary" disabled={disabled || busy} onClick={onClick}>{busy ? "Working…" : label || "Confirm"}</button></div>; }
  return <Modal open onClose={close} title={title} wide={kind === "issue_notice" || kind === "issue_order" || kind === "record_execution"}><div className="space-y-3">{body()}</div></Modal>;
}
